### ISSUE TITLE
Next schedule action not correct

### ISSUE THREAD

**Issue by Inversion-NL** [fabianblom/Toon-Android#6]
Right to the degrees is displayed "At <time> on 0.00". That (0.00) is not correct when on my Toon is "Om 23:00 op Slapen".

More info here:
https://www.domoticaforum.eu/viewtopic.php?f=102&t=11832&view=unread#p90385

**Comment by glsf91** [comment]
It can be fixed by changing nextSetPoint to nextSetpoint
in Toon-Android/app/src/main/java/com/toonapps/toon/entity/ThermostatInfo.java

Reason: output of Toon is:
`{
"result": "ok",
"currentTemp": "1976",
"currentSetpoint": "2000",
"currentInternalBoilerSetpoint": "42",
"programState": "1",
"activeState": "0",
"nextProgram": "1",
"nextState": "2",
"nextTime": "1554151800",
"nextSetpoint": "1500",
"randomConfigId": "1804289383",
"errorFound": "255",
"connection": "0",
"burnerInfo": "1",
"otCommError": "0",
"currentModulationLevel": "0"
}`
